-- 코드를 입력하세요

-- hour에 대한 default value table 생성
WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM TIME
    WHERE HOUR<23
)

SELECT HOUR, COUNT(HOUR(ANIMAL_OUTS.DATETIME)) as COUNT --ANIMAL_OUTS의 개수를 세야 함
FROM TIME LEFT JOIN ANIMAL_OUTS
ON TIME.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY HOUR
